// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webApi.Data;

#nullable disable

namespace webApi.Migrations
{
    [DbContext(typeof(ArtistAlbumSongContext))]
    partial class ArtistAlbumSongContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("webApi.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Artisterid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Namn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Publicerad")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Artisterid");

                    b.ToTable("album");
                });

            modelBuilder.Entity("webApi.Entities.Artister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beskrivning")
                        .HasColumnType("TEXT");

                    b.Property<string>("Namn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("artister");
                });

            modelBuilder.Entity("webApi.Entities.Låtar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Albumid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Namn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Placering")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Albumid");

                    b.ToTable("låtar");
                });

            modelBuilder.Entity("webApi.Entities.Album", b =>
                {
                    b.HasOne("webApi.Entities.Artister", "Artist")
                        .WithMany("Album")
                        .HasForeignKey("Artisterid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("webApi.Entities.Låtar", b =>
                {
                    b.HasOne("webApi.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("Albumid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("webApi.Entities.Artister", b =>
                {
                    b.Navigation("Album");
                });
#pragma warning restore 612, 618
        }
    }
}
